# Protobuf compiler binary
bind(
  name = "protoc",
  actual = "//third_party/protobuf/upstream:protoc"
)

# Library needed to build protobuf codegen plugin.
bind(
  name = "protobuf_compiler",
  actual = "//third_party/protobuf/upstream:protoc_lib",
)

# Library that C++ code generated by protobuf C compiler should depend
# on.
bind(
  name = "protobuf_clib",
  actual = "//third_party/protobuf/upstream:protobuf",
)
